### ISSUE TITLE
Can we have functionality simliar to neatmouse please?

### ISSUE THREAD

**Issue by reddyshyam** [robiot/AlphaClicker#6]
Awesome looking interface there! 👍👌👏

This is a feature request. Can we have functionality similar to neatmouse please? I need a mouse simulator. Please see below

https://neatdecisions.com/products/neatmouse/

**Comment by robiot** [comment]
Thank you and Cool idea! Tho this project is mostly focused on automating mouse clicks. But since its a cool idea I might make another project like netmouse!
